### PR TITLE
multi-scale hexbin geometries

### PR DESCRIPTION
**Pull request by wkhchow**
a stacked set of hexbin boundaries for use in visualizing national exposure and risk datasets at varying scales of resolution. Includes a reference dataset with links between sauid (circa 2019) and hexbin id's to facilitate dynamic aggregation queries.

### CODE REVIEW

**Comment by wkhchow** [comment]
- Current version for testing purposes and load into postgis/ES.  Will require regeneration of new hex bins if we decide to use this method to include a new sauid which was not in the referenced 2019 sauid.

**Review by anthonyfok — APPROVED** [review]
Hi Will,

Murray's latest commits look good to me!
I would suggest removing the .DS_Store file that macOS added, but it is such a minor issue and definitely not worth bothering Murray about it.  I'll be adding `.gitignore` to ignore .DS_Store in a future commit.

Sorry about the false alarm from the gpkg-to-pgdump.yml!  The issue has been dealt with in #15 and with me fixing the B2 public bucket, so all should be good now!

**Comment by anthonyfok** [comment]
Hi @jvanulde, would you like me to revise the GitHub Actions to import these hexbin geometries into our PostGIS database backup too?  Right now, the .github/workflows/gpkg-to-pgdump.yml looks at *.gpkg files in the top-level directory only and ignores any sub-directories, but I can change that behaviour any time.  Please advise.  Thank you!

**Comment by jvanulde** [comment]
> Hi @jvanulde, would you like me to revise the GitHub Actions to import these hexbin geometries into our PostGIS database backup too? Right now, the .github/workflows/gpkg-to-pgdump.yml looks at *.gpkg files in the top-level directory only and ignores any sub-directories, but I can change that behaviour any time. Please advise. Thank you!

Let's leave that up to @wkhchow as I believe we need to update them with the latest SAUID's.

**Review by jvanulde — APPROVED** [review]

**Comment by wkhchow** [comment]
@anthonyfok I would say leave that for now as those hexbins are for testing purposes at the moment and finalized.  If we end up deciding to go with it then I will have to look into generating a new version and perhaps those can go in the top level directory.

**Pull request merged**
